### ISSUE TITLE
[BUG]🔻 positioning incorrect for web vitals.

### ISSUE THREAD

**Issue by xHomu** [metronome-sh/metronome-sh#51]
## Description

🔻 positioning incorrect for web vitals.

## Environment

- Operating System: iOS
- Browser: Safari
- Remix version: v2.0.0-pre.8
- Remix adapter: Express
- Metronome package version (eg: 7.1.0-next.2): @metronome-sh/express@7.1.0-next.12

## Steps to Reproduce

1. https://next.metronome.sh
2. Have LCP at 2
3. ???
4. It's not green.

## Expected Behavior

LCP 2.08 should be in green zone around the 80% mark.

## Actual Behavior

LCP is at yellow zone.

## Screenshots/Logs

<img width="1265" alt="image" src="https://github.com/metronome-sh/metronome-sh/assets/84349818/38ce985f-097c-4201-b9cb-2f225ce2a76e"> 
   
```

```

## Severity

How critical is this issue? 
- [ ] Critical (The product is unusable)
- [ ] High (Blocks you from using the product to its fullest)
- [ ] Moderate (Inconvenient but usable)
- [x] Low (Not urgent)

**Comment by ErickTamayo** [comment]
Thanks! This is fixed, please confirm before I close this issue

**Comment by xHomu** [comment]
Can confirm this is fixed!

![image](https://github.com/metronome-sh/metronome-sh/assets/84349818/df231a43-e143-4b72-ba59-8682ae2c9a48)
