### ISSUE TITLE
[BUG] ERR_UNSUPPORTED_ES_URL_SCHEME On Windows, absolute paths must be valid file:// URLS. Received protocol 'd:" at new NodeError 

### ISSUE THREAD

**Issue by xHomu** [metronome-sh/metronome-sh#52]
## Description

Metronome Next install works fine on iOS environment; on Windows it causes ERR_UNSUPPORTED_ES_URL_SCHEME  error.

## Environment

- Operating System: Windows
- Browser: Chrome
- Remix version: v2.0.0-pre.9
- Remix adapter: Express
- Metronome package version (eg: 7.1.0-next.2): 7.1.0-next.17

## Steps to Reproduce

1. Update Metronome to @next
2. Follow update instructions for `server.ts` and `root.tsx`
3. Build works on iOS/Docker/Linux.
4. ERR_UNSUPPORTED_ES_URL_SCHEME error on Windows environment.

## Expected Behavior

Parity between all three dev environments.

## Actual Behavior

On `yarn dev` and enter localhost, every pageresults in ERR_UNSUPPORTED_ES_URL_SCHEME error.

## Screenshots/Logs

![image](https://github.com/metronome-sh/metronome-sh/assets/84349818/8bafe26e-6148-4f38-88d4-3492fdca71c2)

> Error [ERR_UNSUPPORTED_ES_URL_SCHEME]: Only URLs with a scheme in: file, date, and node are supported by the default ISM loader. On Windows, absolute paths must be valid file:// URLS. Received protocol 'd:" at new NodeError (node:internal/errors:40515)
at throw IfUnsupportedURLScheme (node: Internal/modules/es/load:131:11) at defaultload (node: Internal/modules/esm/load:82:3) at nextload (node: Internal/modules/es/loader: 163:28) at ES Loader.load (node: internal/modules/es/loader: 603:26) at ESHLoader.moduleProvider (node:internal/modules/es/loader: 457:22) at new ModuleJob (node:internal/modules/es/module_job:54:26) at ESPLoader.#createModuleJob (node: internal/modules/esm/loader: 480:17) at ESHLoader.getfloduleJob (node:internal/modules/ese/loader: 434:34) at processTicksAndRejections (node: internal/process/task_queues 95:5)
   

## Severity

How critical is this issue? 
- [x] Critical (The product is unusable)
- [ ] High (Blocks you from using the product to its fullest)
- [ ] Moderate (Inconvenient but usable)
- [ ] Low (Not urgent)

Because we need to support Window devs as well, I have reverted mana.wiki back to v6 for now:

* Successful commit to v6 that clears this error: https://github.com/manawiki/core/commit/89dbf1490158209fd212ce6247c519f28c72c9dc

### Branch that maintains the broken Windows build with metronome@next https://github.com/manawiki/core/tree/metronome-beta-broken-on-windows

PM me @xhomu for the necessary env vars, if you would like to investigate the bug further on the `mana/core` repo.

**Comment by ErickTamayo** [comment]
Fixed in **7.1.0-next.18**

**Comment by xHomu** [comment]
Can confirm metronome beta is working for Windows dev again!

https://github.com/manawiki/core/commit/7f1be29be6382ef3d4bfccda06238bb049088926
