### ISSUE TITLE
[FEATURE REQUEST] Support for Cloudflare with Vite

### ISSUE THREAD

**Issue by sergiodxa** [metronome-sh/metronome-sh#60]
## Feature Description

Allow Remix apps using the Vite plugin and deployed to CF to use Metronome.

## Problem/Situation

I want to setup Metronome on a Remix app I deploy to CF, the app uses Vite but because the Vite plugin for Metronome depends on some Node.js built-in modules it doesn't work.

## Proposed Solution

Change all imports of Node.js built-in to use the `node:` prefix, that way by using the `nodejs_compat` flag in CF it should work.

## Importance

How important is this feature for you?

- [x] Must have
- [ ] Nice to have
- [ ] Enhancement

**Comment by ErickTamayo** [comment]
This will be addressed in the upcoming version soon!

**Comment by ErickTamayo** [comment]
Implemented in https://github.com/metronome-sh/metronome-sh/pull/62
