### ISSUE TITLE
[BUG] `error during build: RollupError: Expected a semicolon` after adding `metronome()`

### ISSUE THREAD

**Issue by caiocmpaes** [metronome-sh/metronome-sh#61]
## Description

I'm following the steps of the [Setting up Metronome Vite plugin](https://metronome.sh/docs/setup-guides/vite.mdoc) and then, once I installed `metronome-sh` to my project and added the plugin call to my `vite.config.js`, It's not building anymore.

## Environment

- Operating System: `Mac OS Sonoma 14.4.1`
- Remix version: `2.8.1`
- Remix adapter: `@remix-run/node 2.8.1`
- Metronome client version: `8.2.1`

## Steps to Reproduce

1. `npm i --save metronome-sh`;
2. `import { metronome } from "metronome-sh/vite"`;
3. Add `metronome()` to my `plugins` list;

Here's my `vite.config.js`:
```
import { vitePlugin as remix } from '@remix-run/dev'
import { metronome } from 'metronome-sh/vite'
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
	server: {
		port: 3000,
	},
	plugins: [
		remix(),
		tsconfigPaths(),
		metronome(),
	],
})
```

Here's my `tsconfig.json`:
```
{
  "include": ["./types/env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "types": ["vitest/globals"],
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "target": "ES2022",
    "strict": true,
    "noImplicitAny": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "paths": {
      "~/*": ["./app/*"]
    },
    "skipLibCheck": true,
    "allowImportingTsExtensions": true,
    "noEmit": true
  }
}

```

## Expected Behavior

What should have happened?
`vite build && vite build --ssr` should have run clean;

(Just removing `metronome()` call, makes my build finish clean again)

## Actual Behavior

What actually happened?

**Build failed `RollupError: Expected a semicolon`**

## Screenshots/Logs
<img width="1270" alt="Captura de Tela 2024-05-02 às 16 10 05" src="https://github.com/metronome-sh/metronome-sh/assets/14334253/7e4996a9-f8b8-4ede-901a-9e5faee2a78d">

## Severity

How critical is this issue? 
- [x] Critical (The product is unusable)
- [ ] High (Blocks you from using the product to its fullest)
- [ ] Moderate (Inconvenient but usable)
- [ ] Low (Not urgent)

**Comment by ErickTamayo** [comment]
Thanks! This will be fixed in the next release coming this weekend

**Comment by ErickTamayo** [comment]
Hello, the semicolon issue should've been solved in https://github.com/metronome-sh/metronome-sh/pull/62. Can you please confirm on your side by updating `metronome-sh` to the latest [8.4.3](https://www.npmjs.com/package/metronome-sh/v/8.4.3)

**Comment by caiocmpaes** [comment]
Huge thanks for the fix and update, @ErickTamayo . I updated the version yesterday night and, indeed, issue is fixed and I'm able to get the data from my website.

Thanks! 😉
