### ISSUE TITLE
[BUG] Unable to complete checkout - infinite "Subscription created" loop

### ISSUE THREAD

**Issue by MrAlex94** [metronome-sh/metronome-sh#71]
## Description

Apologies if this is not the correct place for this, but I'm unable to see another way to contact support.

After completing the checkout process, I am taken to `https://metronome.sh/{Redacted}/billing/success`, which displays the Subscription created page.

And it just redirects indefinitely.

## Environment

- Operating System: macOS 14
- Browser: Waterfox G6.0.14 (same as Firefox ESR 115.10)

## Steps to Reproduce

1. Authenticate with Github
2. Get redirected to Stripe checkout
3. Complete checkout process
4. Get infinite loop.

## Expected Behavior

After initial success message, access to the dashboard.

## Actual Behavior

Infinite loop on successful checkout.

## Screenshots/Logs

<img width="1728" alt="image" src="https://github.com/metronome-sh/metronome-sh/assets/4728920/d471f14a-6cd8-4f4e-9ebe-4a5f57cb1080">

## Severity

How critical is this issue? 
- [x] Critical (The product is unusable)
- [ ] High (Blocks you from using the product to its fullest)
- [ ] Moderate (Inconvenient but usable)
- [ ] Low (Not urgent)

**Comment by ErickTamayo** [comment]
Hey @MrAlex94 , can you shoot me an email erick@metronome.sh so we can share more info there and see what's going on.

**Comment by ErickTamayo** [comment]
Hey @MrAlex94, I found the bug and corrected it. Now it processed the trial correctly. I set it back to 30 days. I apologize for the inconvenience.
