### ISSUE TITLE
Clicking on  'Go to billing portal' gives an application error

### ISSUE THREAD

**Issue by BCarroll524** [metronome-sh/metronome-sh#72]
## Description

I am trying to modify my billing info and i can't because the app errors out.

## Environment

- Operating System: Mac OS
- Browser: Chrome

I'm not sure if there is anything else I can provide to be helpful here. I'm not sure if i'm the only one that has experienced this but we implemented metronome very early on (like ~19 months ago) and haven't really touched it since. Looking to remove it now to reduce costs but am unable to on the website.

https://github.com/metronome-sh/metronome-sh/assets/8650779/93ca2305-5904-4a05-8994-5912d6175880

**Comment by ErickTamayo** [comment]
Hey Blake, Thanks. I'll investigate the error, but for now, I cancelled your subscription. It will end on July 16 at no cost. 

Hit me at erick@metronome.sh if you'd like to keep using Metronome. If you find it useful I can give you credits or some other arrangement to keep using it as long as you feel like it. No commitments.
