### ISSUE TITLE
[BUG] Going to the billing portal results in an application error (I can't cancel my account)

### ISSUE THREAD

**Issue by silvenon** [metronome-sh/metronome-sh#73]
## Description

Hey, I like Metronome, but I currently have no app to use it on, and I need to cut down on my expenses, so I'd like to cancel my account. The billing portal is the only place which might have this functionality, and it currently consistently results in an application error page.

## Steps to Reproduce

1. have a user on a Metronome Solo plan
2. click on the "Go to billing portal" button

## Screenshots/Logs

<img width="296" alt="Screenshot 2024-08-02 at 11 28 47" src="https://github.com/user-attachments/assets/792ef3f9-88d0-4f21-947c-f261b64dfea7">

## Severity

How critical is this issue? 
- [x] Critical (The product is unusable)
- [ ] High (Blocks you from using the product to its fullest)
- [ ] Moderate (Inconvenient but usable)
- [ ] Low (Not urgent)

**Comment by ErickTamayo** [comment]
Hello @silvenon, I manually cancelled the subscription and waived this period, so you won't be billed. Sorry about the bug. I'll take a look at it ASAP

**Comment by silvenon** [comment]
Thanks!
